### ISSUE TITLE
Issue: 400 Unsupported parameter: 'max_tokens' using model 'o1-preview'

### ISSUE THREAD

**Issue by Prem95** [langchain-ai/langsmith-sdk#1003]
### Issue you'd like to raise.

Changed the model in Playground to use o1-preview (I have Tier 5 support) but received this error instead

```
400 Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.

Error: 400 Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.
    at APIError.generate (file:///node_modules/openai/error.mjs:41:20)
    at OpenAI.makeStatusError (file:///node_modules/openai/core.mjs:268:25)
    at OpenAI.makeRequest (file:///node_modules/openai/core.mjs:311:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///node_modules/@langchain/openai/dist/chat_models.js:881:29
    at async RetryOperation._fn (/node_modules/p-retry/index.js:50:12)
```

### Suggestion:

Support for new model from OpenAI

**Comment by dennisofficial** [comment]
For me, I'm just not getting any traces from `o1-preview`

**Comment by hinthornw** [comment]
@dennisofficial do you have code to share for that?

**Comment by Prem95** [comment]
Any updates here? Thanks!

**Comment by MiNeves00** [comment]
any new updates? i am also seeing the same error

**Comment by ChampPhil** [comment]
Any new updates? I am also encoutering a similar error with the 'parallel_tool_calls' parameter
