### ISSUE TITLE
Can't run o1-preivew and o1-mini models in the langsmith playground

### ISSUE THREAD

**Issue by ogamaniuk** [langchain-ai/langsmith-sdk#1120]
### Issue you'd like to raise.

![image](https://github.com/user-attachments/assets/11fc15ea-8ee6-46a8-8ccf-af3bba25ad5e)

Here's the error message:

BadRequestError('Error code: 400 - {\'error\': {\'message\': "Unsupported value: \'stream\' does not support true with this model. Only the default (false) value is supported.", \'type\': \'invalid_request_error\', \'param\': \'stream\', \'code\': \'unsupported_value\'}}')Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2303, in _atransform_stream_with_config

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3385, in _atransform

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 5573, in atransform

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1473, in atransform

  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 494, in astream

  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 472, in astream

  File "/usr/local/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 2015, in _astream

  File "/usr/local/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 785, in _astream

  File "/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/openai/patch.py", line 289, in patched_endpoint
    resp = await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1490, in create

  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1831, in post

  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1525, in request

  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1626, in _request

openai.BadRequestError: Error code: 400 - {'error': {'message': "Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.", 'type': 'invalid_request_error', 'param': 'stream', 'code': 'unsupported_value'}}

**Comment by gautamm20** [comment]
This is a major annoyance. Can be fixed with the correct pydantic validation.

**Comment by alex00x0** [comment]
have u tried deactivating stream as shown here?
https://langchain-ai.github.io/langgraph/how-tos/disable-streaming/?h=o1#disabling-streaming

**Comment by rhlarora84** [comment]
How is `disable_streaming` different from the `streaming` flag on the ChatOpenAI.
