### ISSUE TITLE
Issue: Traces with large images frequently fail by timeout

### ISSUE THREAD

**Issue by jacob-israel-turner** [langchain-ai/langsmith-sdk#1245]
### Issue you'd like to raise.

When submitting traces for runs with images, I often get a timeout failure:
```
DOMException [TimeoutError]: The operation was aborted due to timeout
    at node:internal/deps/undici/undici:13185:13
    at RetryOperation._fn (/Users/jacob/code/mithra/mithra/node_modules/.pnpm/p-retry@4.6.2/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 7,
  retriesLeft: 0
}
```

Related issue: #1101 

### Suggestion:

- #1113 may fix this issue
- Allow consumers to opt-out of sending images with traces (the rest of the trace could be preserved)
- Allow consumers to suppress tracing failures logging in the console

**Comment by zirkelc** [comment]
Not sure if it's the same issue, but we also see errors like this:

```sh
WARN	Failed to multipart ingest runs: TimeoutError: The operation was aborted due to timeout
    at node:internal/deps/undici/undici:13185:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processTimers (node:internal/timers:516:9)
    at async RetryOperation._fn (/node_modules/.pnpm/p-retry@4.6.2/node_modules/p-retry/index.js:50:12)
```

**Comment by jacoblee93** [comment]
Starting a new PR for this

**Comment by Rafik-Belkadi-malou** [comment]
Still getting a lot of errors, i have set the timeout to 10 sec but even when increasing to 20/30 (openai o4-mini) or completly removing the timeout, it goes to 1/2 minutes and fails :

<img width="1064" alt="Image" src="https://github.com/user-attachments/assets/54971ada-63d8-4317-b41e-efd3a1aacddf" />

**Comment by pridapablo** [comment]
I get a similar error when trying to trace text chains

<img width="1122" alt="Image" src="https://github.com/user-attachments/assets/e6a976d5-7fdd-45d5-bc50-24e6199c18f5" />

The UI stays in status pending and eventually gets an orange cross

<img width="1582" alt="Image" src="https://github.com/user-attachments/assets/e13665e5-4859-40d4-ad49-7cd6421aa749" />

**Comment by eric-langchain** [comment]
We released multi part upload which helps mitigate this issue. if you're still seeing it, please reopen
