### ISSUE TITLE
DOC: Update python getting started docs for openai >= 1.0.0

### ISSUE THREAD

**Issue by gabrielchua** [langchain-ai/langsmith-sdk#354]
### Issue with current documentation:

I am following the example on logging Traces Outside LangChain [here](https://github.com/langchain-ai/langsmith-sdk/blob/main/python/README.md#logging-traces-outside-langchain).

### Idea or request for content:

The line:
```
argument_chain("Why is blue better than orange?")
```

results in the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dsaid/.pyenv/versions/personal/lib/python3.11/site-packages/langsmith/run_helpers.py", line 399, in wrapper
    raise e
  File "/Users/dsaid/.pyenv/versions/personal/lib/python3.11/site-packages/langsmith/run_helpers.py", line 395, in wrapper
    function_result = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "<stdin>", line 3, in argument_chain
  File "/Users/dsaid/.pyenv/versions/personal/lib/python3.11/site-packages/langsmith/run_helpers.py", line 399, in wrapper
    raise e
  File "/Users/dsaid/.pyenv/versions/personal/lib/python3.11/site-packages/langsmith/run_helpers.py", line 395, in wrapper
    function_result = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "<stdin>", line 3, in argument_generator
  File "/Users/dsaid/.pyenv/versions/personal/lib/python3.11/site-packages/langsmith/run_helpers.py", line 399, in wrapper
    raise e
  File "/Users/dsaid/.pyenv/versions/personal/lib/python3.11/site-packages/langsmith/run_helpers.py", line 395, in wrapper
    function_result = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "<stdin>", line 3, in call_openai
  File "/Users/dsaid/.pyenv/versions/personal/lib/python3.11/site-packages/openai/lib/_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1:

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
```

Will langsmith support `openai` >= `1.0.0` or should the documentation be updated? 

Thank you!

**Comment by hinthornw** [comment]
LangSmith is openai version agnostic so version 1.0.0 works well! I'll update the docs. Thanks!

**Comment by hinthornw** [comment]
should all be refreshed
