### ISSUE TITLE
Issue:  "TypeError: object.__init__() takes exactly one argument (the instance to initialize)"

### ISSUE THREAD

**Issue by FloweryScythe13** [langchain-ai/langsmith-sdk#505]
### Issue you'd like to raise.

Hello, 

I am setting up a CI pipeline for a LangSmith evaluation using GitHub Actions. This is for a LangChain application if it matters. My GH Action is receiving an error from the LangSmith client and from the `langchain.smith` package which I am unable to resolve on my own: 

```
...
View all tests for Dataset My Second FreshQA Dataset at:
https://smith.langchain.com/o/e2b59d30-b1d3-4e34-bcdb-00466fce9cb3/datasets/a64ec8eb-0c9d-4671-8f3d-a6d17d9a2ea3
Traceback (most recent call last):

  File "/home/runner/work/my-app/my-app/tests/langsmith_evaluator.py", line 116, in <module>
    main()
  File "/home/runner/work/my-app/my-app/tests/langsmith_evaluator.py", line 96, in main
    chain_results = client.run_on_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/langsmith/client.py", line [32](https://github.com/True-Global/my-app/actions/runs/8165348509/job/22322341279#step:7:33)53, in run_on_dataset
    return _run_on_dataset(
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/langchain/smith/evaluation/runner_utils.py", line 12[45](https://github.com/True-Global/my-app/actions/runs/8165348509/job/22322341279#step:7:46), in run_on_dataset
    container = _DatasetRunContainer.prepare(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/langchain/smith/evaluation/runner_utils.py", line 1097, in prepare
    configs = [
              ^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/langchain/smith/evaluation/runner_utils.py", line 1100, in <listcomp>
    LangChainTracer(
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/langchain_core/tracers/langchain.py", line 86, in __init__
    super().__init__(**kwargs)
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/langchain_core/tracers/base.py", line 67, in __init__
    super().__init__(**kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
[>                                                 ] 0/116
Error: Process completed with exit code 1.
```

My code being run is below: 

```python
from langsmith.evaluation import EvaluationResult, run_evaluator
from langsmith.schemas import Example, Run
from langchain.evaluation import EvaluatorType
from langchain.smith import RunEvalConfig
import functools
from langsmith import Client
from langchain.smith import arun_on_dataset, run_on_dataset
from my_app.utils import init_agent
import os
from uuid import uuid4
from decouple import config


@run_evaluator
def check_not_idk(run: Run, example: Example):
    """Illustration of a custom evaluator."""
    agent_response = run.outputs["output"]
    if "don't know" in agent_response or "not sure" in agent_response:
        score = 0
    else:
        score = 1
    return EvaluationResult(
        key="not_uncertain",
        score=score,
    )

dataset_name = "My Second FreshQA Dataset"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"

os.environ["LANGCHAIN_API_KEY"] = "<my API key>"

def input_mapper(dataset_row):
    """
    Transforms a single dataset row to match the input structure expected by the agent.
    For simplicity, chat_history is passed as an empty dictionary.
    
    Args:
        dataset_row (dict): A single row from the dataset.
        
    Returns:
        dict: Transformed input for the agent.
    """

    return {
        "input": dataset_row["question"],
        "chat_history": [],  # Pass an empty list for chat_history
    }

def main():
    os.environ["OPENAI_API_KEY"] = config("OPENAI_API_KEY")
    evaluation_config = RunEvalConfig(
        # Evaluators can either be an evaluator type (e.g., "qa", "criteria", "embedding_distance", etc.) or a configuration for that evaluator
        evaluators=[
            EvaluatorType.QA,
            EvaluatorType.EMBEDDING_DISTANCE,
            RunEvalConfig.LabeledCriteria("helpfulness"),
            RunEvalConfig.LabeledScoreString(
                {
                    "accuracy": """
    Score 1: The answer is completely unrelated to the reference.
    Score 3: The answer has minor relevance but does not align with the reference.
    Score 5: The answer has moderate relevance but contains inaccuracies.
    Score 7: The answer aligns with the reference but has minor errors or omissions.
    Score 10: The answer is completely accurate and aligns perfectly with the reference."""
                },
                normalize_by=10,
            ),
        ],
        input_key="input",
        custom_evaluators=[check_not_idk],
    )
    
    client = Client()
    unique_id = uuid4().hex[0:8]
    
    chain_results = client.run_on_dataset(
        dataset_name=dataset_name,
        llm_or_chain_factory=init_agent(verbose=False),
        evaluation=evaluation_config,
        verbose=True,
        input_mapper=input_mapper,
        concurrency_level=5,
        project_name=f"runnable-agent-test-5d466cbc-{unique_id}",
        # Project metadata communicates the experiment parameters,
        # Useful for reviewing the test results
        project_metadata={
            "env": "testing-notebook",
            "model": "gpt-3.5-turbo",
            "prompt": "5d466cbc",
        },
    )
    
if __name__ == "__main__":
    main()
```

Since this issue appears at first glance to be coupled between `langsmith-sdk` and `langchain_core`, and thus perhaps not immediately fixable, is there any way I can work around this error in my code for the moment?

**Comment by hinthornw** [comment]
What versions of langsmith/langchain are you using?

**Comment by FloweryScythe13** [comment]
That may indeed be the case. In my local environment, where the langsmith eval script works, I am using langchain==0.0.354, langchain-core==0.1.16, and langsmith==0.0.83. In my GH Action workflow, it was using langchain==0.0.354, langchain-core==0.1.23, and langsmith==0.0.87. I am able to now reproduce the above error locally by upgrading my versions of langsmith and core.
