### ISSUE TITLE
Issue: No child runs when evaluating agent behind langserve endpoint

### ISSUE THREAD

**Issue by Blubberblub** [langchain-ai/langsmith-sdk#591]
### Issue you'd like to raise.

I'm running an agent through a langserve endpoint and i have a testing dataset in langsmith for which i want to evaluate if tools are used when calling the endpoint.

The how-to section in the docs indicates that the tool calls for nested runs are found in the `child_runs` of the run object when using an evaluator in the `evaluate` function from langsmith.

However when i use my evaluator in the `evaluate` function and print the run object, the `child_runs` is only an empty list even though the final answers clearly indicate that a tool must have been used.

Some sample code:
```
from langserve import RemoteRunnable
from langsmith.evaluation import evaluate
from langsmith.schemas import Example, Run


remote_runnable = RemoteRunnable("http://localhost:8000/")

def predict(inputs: dict):
    return remote_runnable.invoke(inputs)

def evaluate_trajectory(run: Run, example: Example) -> dict:
    # collect the tools on level 1 of the trace tree
    print(run)
    steps = [child.name for child in run.child_runs if child.run_type == "tool"]
    print(steps)
    # dummy return for now
    return {"key": "tools", "score": 0}

evaluate(
    predict,
    data="test questions",
    evaluators=[evaluate_trajectory],
)
```

**Comment by hinthornw** [comment]
Have you set `include_callback_events=True` in your endpoint? Otherwise the client has no way of viewing what goes on within the server

**Comment by Blubberblub** [comment]
@hinthornw Thanks for the quick reply. I tried both of your solutions. Using `include_callback_events=True` in my endpoint gave me some weird issues related to typing (see log in the end of the post). Using `evaluate` directly on my agent executor still gave me empty child_runs.

the last lines of the error log:
```
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/langserve/server.py", line 481, in invoke
    return await api_handler.invoke(request)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/langserve/api_handler.py", line 740, in invoke
    self._InvokeResponse(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 27 validation errors for InvokeResponse
callback_events -> 15 -> __root__ -> serialized
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_chain_start' (type=value_error.const; given=on_agent_finish; permitted=('on_chain_start',))
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_chain_end' (type=value_error.const; given=on_agent_finish; permitted=('on_chain_end',))
callback_events -> 15 -> __root__ -> error
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_chain_error' (type=value_error.const; given=on_agent_finish; permitted=('on_chain_error',))
callback_events -> 15 -> __root__ -> serialized
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> messages
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_chat_model_start' (type=value_error.const; given=on_agent_finish; permitted=('on_chat_model_start',))
callback_events -> 15 -> __root__ -> serialized
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> prompts
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_llm_start' (type=value_error.const; given=on_agent_finish; permitted=('on_llm_start',))
callback_events -> 15 -> __root__ -> response
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_llm_end' (type=value_error.const; given=on_agent_finish; permitted=('on_llm_end',))
callback_events -> 15 -> __root__ -> serialized
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> input_str
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_tool_start' (type=value_error.const; given=on_agent_finish; permitted=('on_tool_start',))
callback_events -> 15 -> __root__ -> output
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_tool_end' (type=value_error.const; given=on_agent_finish; permitted=('on_tool_end',))
callback_events -> 15 -> __root__ -> error
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_tool_error' (type=value_error.const; given=on_agent_finish; permitted=('on_tool_error',))
callback_events -> 15 -> __root__ -> serialized
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> query
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_retriever_start' (type=value_error.const; given=on_agent_finish; permitted=('on_retriever_start',))
callback_events -> 15 -> __root__ -> documents
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_retriever_end' (type=value_error.const; given=on_agent_finish; permitted=('on_retriever_end',))
callback_events -> 15 -> __root__ -> error
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_retriever_error' (type=value_error.const; given=on_agent_finish; permitted=('on_retriever_error',))
```

**Comment by Blubberblub** [comment]
@hinthornw Yes i tried that but got quite a few typing errors, so i wanted to make sure.

The Chain runs on the server but there is issues after it finishes:
```
> Finished chain.
INFO:     127.0.0.1:35724 - "POST /invoke HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/langserve/server.py", line 481, in invoke
    return await api_handler.invoke(request)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.10/site-packages/langserve/api_handler.py", line 740, in invoke
    self._InvokeResponse(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 27 validation errors for InvokeResponse
callback_events -> 15 -> __root__ -> serialized
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_chain_start' (type=value_error.const; given=on_agent_finish; permitted=('on_chain_start',))
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_chain_end' (type=value_error.const; given=on_agent_finish; permitted=('on_chain_end',))
callback_events -> 15 -> __root__ -> error
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_chain_error' (type=value_error.const; given=on_agent_finish; permitted=('on_chain_error',))
callback_events -> 15 -> __root__ -> serialized
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> messages
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_chat_model_start' (type=value_error.const; given=on_agent_finish; permitted=('on_chat_model_start',))
callback_events -> 15 -> __root__ -> serialized
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> prompts
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_llm_start' (type=value_error.const; given=on_agent_finish; permitted=('on_llm_start',))
callback_events -> 15 -> __root__ -> response
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_llm_end' (type=value_error.const; given=on_agent_finish; permitted=('on_llm_end',))
callback_events -> 15 -> __root__ -> serialized
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> input_str
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_tool_start' (type=value_error.const; given=on_agent_finish; permitted=('on_tool_start',))
callback_events -> 15 -> __root__ -> output
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_tool_end' (type=value_error.const; given=on_agent_finish; permitted=('on_tool_end',))
callback_events -> 15 -> __root__ -> error
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_tool_error' (type=value_error.const; given=on_agent_finish; permitted=('on_tool_error',))
callback_events -> 15 -> __root__ -> serialized
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> query
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_retriever_start' (type=value_error.const; given=on_agent_finish; permitted=('on_retriever_start',))
callback_events -> 15 -> __root__ -> documents
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_retriever_end' (type=value_error.const; given=on_agent_finish; permitted=('on_retriever_end',))
callback_events -> 15 -> __root__ -> error
  field required (type=value_error.missing)
callback_events -> 15 -> __root__ -> type
  unexpected value; permitted: 'on_retriever_error' (type=value_error.const; given=on_agent_finish; permitted=('on_retriever_error',))
```

**Comment by Blubberblub** [comment]
@hinthornw Is there anything new on this issue or anything i can provide to fix it?

**Comment by hinthornw** [comment]
Were you able to resolve the `include_callbacks` issue?

If so, try updating langchain core here - child_runs traced within langchain code should now be included in your langsmith run tree

**Comment by Blubberblub** [comment]
@hinthornw Thanks for the reply and your effort! With the new langchain_core i now get the nested traces when doing eval with the `AgentExecutor `directly (no langserve). So i have at least one way of making the evaluation work. For the langserve issue i got a reply from support wich says "this is a gap right now in langserve's capabilities", so i will not test further for now. I think this issue can be closed. Again thanks for looking at it!
