### ISSUE TITLE
Issue: "Session already exists" error when trying to run evaluation

### ISSUE THREAD

**Issue by msamogh** [langchain-ai/langsmith-sdk#814]
### Issue you'd like to raise.

I've previously used the Python SDK to run evaluation over a dataset. Using the **same** code, I'm now trying to run an evaluation after a few days, but get the following error.

`requests.exceptions.HTTPError: [Errno 409 Client Error: Conflict for url: https://api.smith.langchain.com/sessions] {"detail":"Session already exists."}`

I have even tried doing a `kill -9` of Python processes in case a previous one was lingering around. Please help.

Full Stack Trace below:
```
(classroom) (base) msamogh:classroom amogh.mannekote$ python src/main.py 
Traceback (most recent call last):
  File "/Users/amogh.mannekote/miniconda3/envs/classroom/lib/python3.11/site-packages/langsmith/utils.py", line 121, in raise_for_status_with_text
    response.raise_for_status()
  File "/Users/amogh.mannekote/miniconda3/envs/classroom/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.smith.langchain.com/sessions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/amogh.mannekote/classroom/src/main.py", line 26, in <module>
    ).run()
      ^^^^^
  File "/Users/amogh.mannekote/classroom/src/sweep.py", line 206, in run
    experiment_name = self._predict_over_dataset(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amogh.mannekote/classroom/src/sweep.py", line 107, in _predict_over_dataset
    results = evaluate(
              ^^^^^^^^^
  File "/Users/amogh.mannekote/miniconda3/envs/classroom/lib/python3.11/site-packages/langsmith/evaluation/_runner.py", line 239, in evaluate
    return _evaluate(
           ^^^^^^^^^^
  File "/Users/amogh.mannekote/miniconda3/envs/classroom/lib/python3.11/site-packages/langsmith/evaluation/_runner.py", line 798, in _evaluate
    ).start()
      ^^^^^^^
  File "/Users/amogh.mannekote/miniconda3/envs/classroom/lib/python3.11/site-packages/langsmith/evaluation/_runner.py", line 1071, in start
    project = self._get_project(first_example)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amogh.mannekote/miniconda3/envs/classroom/lib/python3.11/site-packages/langsmith/evaluation/_runner.py", line 951, in _get_project
    raise e
  File "/Users/amogh.mannekote/miniconda3/envs/classroom/lib/python3.11/site-packages/langsmith/evaluation/_runner.py", line 943, in _get_project
    project = self.client.create_project(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amogh.mannekote/miniconda3/envs/classroom/lib/python3.11/site-packages/langsmith/client.py", line 2006, in create_project
    ls_utils.raise_for_status_with_text(response)
  File "/Users/amogh.mannekote/miniconda3/envs/classroom/lib/python3.11/site-packages/langsmith/utils.py", line 123, in raise_for_status_with_text
    raise requests.HTTPError(str(e), response.text) from e  # type: ignore[call-arg]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
requests.exceptions.HTTPError: [Errno 409 Client Error: Conflict for url: https://api.smith.langchain.com/sessions] {"detail":"Session already exists."}
```

**Comment by hinthornw** [comment]
Should be resolved!
