### ISSUE TITLE
Issue: Error when using two consecutive tools on playground ChatAnthropic claude-3-5-sonnet-20240620 

### ISSUE THREAD

**Issue by GuilhermeKO** [langchain-ai/langsmith-sdk#899]
### Issue you'd like to raise.

The following error occurs when creating consecutive AI messages with tool calls followed by Tool Messages:

400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.3.content.0.tool_use.name: String should match pattern '^[a-zA-Z0-9_-]{1,64}$'"}}

Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.3.content.0.tool_use.name: String should match pattern '^[a-zA-Z0-9_-]{1,64}$'"}}
    at APIError.generate (file:///node_modules/@anthropic-ai/sdk/error.mjs:36:20)
    at Anthropic.makeStatusError (file:///node_modules/@anthropic-ai/sdk/core.mjs:256:25)
    at Anthropic.makeRequest (file:///node_modules/@anthropic-ai/sdk/core.mjs:299:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/node_modules/p-retry/index.js:50:12

**Steps to Reproduce:**

Provider:  ChatAnthropic
Model: claude-3-5-sonnet-20240620 

1. Create a AI message with tool call: 

tool name: getOrderData
tool id :  toolu_018kq2eUEPncj2jBeEodys4Q
```
{
  "days": 30,
  "unfinisehd_orders": "false"
}

```

2. Then the Tool message with the response:

tool name: getOrderData
tool id: toolu_018kq2eUEPncj2jBeEodys4Q
```
[
  {
    "orderCode": "123456789",
    "orderDate": "11/07/2024",
    "status": "Canceled",
    "deliveryDate": "12/07/2024",
    "origin": "Test1",
    "orderPrice": 20.01
  }
]
```
Note: Works fine until this point.

3. Now create another AI message with tool call:
tool name: authenticate_user
tool id :  toolu_01D1GYt1s5UhtKd2dNQydjY5
```
{
  "user_info": "1234567890",
  "password": "password"
}
```

4. And another Tool message with response:
tool name: authenticate_user
tool id :  toolu_01D1GYt1s5UhtKd2dNQydjY5
```
"Authenticated"
```

Running this generates the error above mentioned.
I have tried changing the tools names as the error suggests and tried changing the order of tools but nothing changed.
Both tools work when there is no consecutive tool.

Screenshot with initial AI and Tool Message:
![image](https://github.com/user-attachments/assets/1d268e09-de4d-4973-84ef-3cd0b0eb8e4d)

Screenshot with The consecutive Ai and Tool Messages:
![image](https://github.com/user-attachments/assets/0251e9ed-2fcc-4fbb-805c-e70196fec77d)

Screenshot with Error:
![image](https://github.com/user-attachments/assets/d54df07f-fd06-48c2-9b37-82a4a5b61e7f)

**Comment by hinthornw** [comment]
Thanks for raising! Could you share a link to an example trace where this occurs?

**Comment by GuilhermeKO** [comment]
Sure thing! Here's the link: https://smith.langchain.com/public/89acdb04-c7ce-4dff-b6ca-5bb872138683/r

**Comment by GuilhermeKO** [comment]
Sure thing! Here is the link: https://smith.langchain.com/public/3537d35c-9ff2-445f-92bf-94586c0874b3/r

**Comment by hinthornw** [comment]
@GuilhermeKO if you look at the tool names, you'll see there's an invalid space in your tool name there:
```
"tool_calls": [
                        {
                            "name": "authenticate_user ",
                            "args": {
                                "cpf_or_cnpj": "12345678900",
                                "password": "Senha12345"
                            },
                            "id": "toolu_01D1GYt1s5UhtKd2dNQydjY5"
                        }
                    ],
```

Notice the `"authenticate_user "`
